spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.3.131:9092,192.168.3.132:9092,192.168.3.133:9092
      group-id: iot-web-platform
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: cn.com.ycig.tiisp.haikang.server.kafka.RawMessageDecoder